In [1]:
from __future__ import print_function
import matplotlib.pyplot as plt

import numpy as np
import pandas as pd
import tflearn

curses is not supported on this machine (please install/reinstall curses for an optimal experience)








In [2]:
# Load CSV file, indicate that the first column represents labels
from tflearn.data_utils import load_csv
data, labels = load_csv('complete_data.csv', target_column=0,
                        categorical_labels=False)

In [3]:
data

[['144.8348601347096',
  '3.268655699231537',
  '0.01531802914205926',
  '2.53323208546744',
  '0.3909649114936354'],
 ['240.68785550713784',
  '0.05877885411138582',
  '0.011315414846228361',
  '1.9784638311039155',
  '0.4799454920305853'],
 ['370.7138448931088',
  '0.5045661399799317',
  '0.011283791383929813',
  '1.4823953088663684',
  '0.8549012126898684'],
 ['412.9634980873544',
  '1.1475596741199485',
  '0.010835312314175203',
  '2.7261387582974175',
  '0.12617569948548635'],
 ['579.8016993590546',
  '0.1399990372398016',
  '0.01608981262646446',
  '2.6401519271605616',
  '0.6360644992371949'],
 ['323.77861489714184',
  '0.5858665108626402',
  '0.027764925407007774',
  '1.4722823381850534',
  '0.0941492760080683'],
 ['535.3267566583637',
  '0.7837412772868085',
  '0.024344799310800167',
  '1.4273072686258452',
  '0.3909310104613857'],
 ['370.6018525187842',
  '0.13188091595530832',
  '0.024688427269722018',
  '2.4805792956053128',
  '0.41992589084088106'],
 ['295.23940847034805',

In [4]:
data2 = pd.read_csv('complete_data.csv')

In [5]:
labels

['2.3166009723901224',
 '5.221577038921476e-07',
 '0.10737693038929248',
 '0.2029009822975536',
 '0.004173824758240641',
 '1.3957243025926122e-07',
 '0.0860122480875646',
 '9.42056737143526e-05',
 '0.011026206951032914',
 '0.024056150226947043',
 '0.2641385748765056',
 '0.505597849368516',
 '2.57785397928682',
 '0.00015852773145761992',
 '0.27066443436323395',
 '0.03502985836067314',
 '1.9008071448081534e-63',
 '0.19695691083750447',
 '3.407922370786042e-08',
 '0.2888417424555419',
 '0.23194121954562102',
 '0.06786120859076994',
 '0.0019861329410993016',
 '1.543961387742686',
 '6.446345388721976',
 '0.002157564771833984',
 '4.088966231645902',
 '0.38513917192646474',
 '3.231106261345731e-08',
 '0.0003931876653225817',
 '0.31367379982771076',
 '0.23771127718226148',
 '4.619676977116801',
 '0.11727542028747558',
 '1.9164232506126824',
 '0.365104248929743',
 '3.5185075821252783',
 '0.00033061268373077587',
 '0.0006065016822727133',
 '0.2841148886203689',
 '1.159477997315648',
 '0.17052091

In [6]:
# Preprocessing function
def preprocess(data):
    # Sort by descending id and delete columns
    #for id in sorted(columns_to_ignore, reverse=True):
       # [r.pop(id) for r in data]
    #for i in range(len(data)):
      # Converting 'sex' field to float (id is 1 after removing labels column)
      #data[i][1] = 1. if data[i][1] == 'female' else 0.
    return np.array(data, dtype=np.float32)

In [7]:
# Ignore 'name' and 'ticket' columns (id 1 & 6 of data array)
to_ignore=[7]

In [8]:
# Preprocess data
data = preprocess(data)

In [9]:
data[1]

array([2.4068785e+02, 5.8778856e-02, 1.1315415e-02, 1.9784639e+00,
       4.7994548e-01], dtype=float32)

In [10]:
labels[1]

'5.221577038921476e-07'

In [11]:
labels = np.reshape(labels, (-1, 1))

In [12]:
labels

array([['2.3166009723901224'],
       ['5.221577038921476e-07'],
       ['0.10737693038929248'],
       ...,
       ['1.7871291390065658'],
       ['0.00016757489607586884'],
       ['0.8469105727553061']], dtype='<U23')

In [13]:
# Build neural network
rmsprop = tflearn.optimizers.RMSProp (learning_rate=0.001, decay=0.9, momentum=0.0, epsilon=1e-10, use_locking=False, name='RMSProp')
net = tflearn.input_data(shape=[None, 5])
net = tflearn.fully_connected(net, 32, activation = 'LeakyReLU')
net = tflearn.fully_connected(net, 32, activation = 'ELU')
net = tflearn.dropout(net,.75)
net = tflearn.fully_connected(net, 32, activation = 'ReLU')
net = tflearn.dropout(net,.75)
net = tflearn.fully_connected(net, 1, activation='ELU')
net = tflearn.regression(net, optimizer = rmsprop)

#net = tflearn.input_data(shape=[None, 5])
#net = tflearn.fully_connected(net, 32, activation = 'LeakyReLU')
#net = tflearn.dropout(net,.75)
#net = tflearn.fully_connected(net, 32, activation = 'ELU')
#net = tflearn.dropout(net,.75)
#net = tflearn.fully_connected(net, 32, activation = 'ReLU')
#net = tflearn.dropout(net,.75)
#net = tflearn.fully_connected(net, 1, activation = 'ELU')
#net = tflearn.dropout(net,.75)
#net = tflearn.regression(net)


Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.

Instructions for updating:
keep_dims is deprecated, use keepdims instead


In [14]:
# Define model
model = tflearn.DNN(net, tensorboard_verbose=3)
# Start training (apply gradient descent algorithm)
model.fit(data, labels, n_epoch=10, batch_size=16, show_metric=True)

Training Step: 187499  | time: 116.228s
| RMSProp | epoch: 010 | loss: 0.00000 - binary_acc: 0.0000 -- iter: 299984/300000
Training Step: 187500  | time: 116.234s
| RMSProp | epoch: 010 | loss: 0.00000 - binary_acc: 0.0000 -- iter: 300000/300000
--


In [15]:
model.predict_label(data)

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]], dtype=int64)

In [16]:
X = [4.5487756e+02, 3.7073444e+02, 2.6491962e-02, 1.3647598e+00,
        2.8968331e-01]

In [17]:
X = np.reshape(X, (-1, 5))

In [18]:
print(X)

[[4.5487756e+02 3.7073444e+02 2.6491962e-02 1.3647598e+00 2.8968331e-01]]


In [19]:
model.predict(X)

array([[0.08936229]], dtype=float32)

In [20]:
length_of_data = len(data)

In [21]:
print(data[1])

[2.4068785e+02 5.8778856e-02 1.1315415e-02 1.9784639e+00 4.7994548e-01]


In [22]:
loss_list = []
#for i in range(length_of_data):
data_value = data[0] 
print(data_value)


[1.4483485e+02 3.2686558e+00 1.5318030e-02 2.5332320e+00 3.9096493e-01]


In [23]:
data_value = np.reshape(data_value, (-1, 5))
predicted_value = model.predict(data_value)


#plt.hist(loss_list, bins = 10)   

In [24]:
print(predicted_value)

[[0.08716277]]


In [25]:
labels[0]

array(['2.3166009723901224'], dtype='<U23')